services:
  postgres:
    image: postgres:17
    container_name: vitrio-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: vitrio
      POSTGRES_USER: vitrio
      POSTGRES_PASSWORD: vitrio123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: vitrio-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vitrio.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      - postgres

volumes:
  postgres_data: